# This file was generated by GoReleaser. DO NOT EDIT.
cask "ravion" do
  version "1.14.3"

  on_macos do
    on_arm do
      sha256 "e17daaa595c4b302dbe2f16c2b2981a1e4cc846bfcf75f4d1f0f7e0937a6b5bd"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e2845340166407581aeb6db9d99eb5ae7fa91bf9e7920fc05d86f8df163efa9d"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "21c84aa2c1269d041e538d895ff97e16cd4bf7951fe63bb8dfe4eddef8649f2d"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b20d142cc8727306834515587f32da51187aa856b62fc09ad57ce100a2bf3b3c"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "ravion"
  desc "Ravion CLI"
  homepage "https://ravion.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ravion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ravion"]
    end
  end

  # No zap stanza required
end
