# This file was generated by GoReleaser. DO NOT EDIT.
cask "ravion" do
  version "1.14.11"

  on_macos do
    on_arm do
      sha256 "9372a2cd4248f9339338b86b686935b19c0db464974a3edc482cc045b3666f32"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0407372014b3f92cb5cbcec9ab44ae5d7c169faf1caa2b468d6d08d1b729269a"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "edaa5a4a17608c609f3601299cff62947665e06047abb3636e064163e9f1f7d1"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "99331a878cb89b71c1f9cfaf8ea665eb9809762b2fd1ff669a35ddd9173e826d"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "ravion"
  desc "Ravion CLI"
  homepage "https://ravion.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ravion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ravion"]
    end
  end

  # No zap stanza required
end
