# This file was generated by GoReleaser. DO NOT EDIT.
cask "ravion" do
  version "1.14.9"

  on_macos do
    on_arm do
      sha256 "0380d091824b4a103f2df1c137097649c2d5ad9355fe669a6e9541cb29ae4747"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8249c4ea97c62b0858bf368a5dd04fbf1ce32b3d14261e4cd2b2e96d2a1e33c9"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c6779750bd65d4cafc2b3670a7a46d9fdf26db96a3cc4d638c10449af6ef2e56"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "82c6da819697d04d4088b3c72fbc74aaa6a623400c307c17ef237434660a8ee5"
      url "https://github.com/ravionhq/cli/releases/download/v#{version}/ravion_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "ravion"
  desc "Ravion CLI"
  homepage "https://ravion.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ravion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ravion"]
    end
  end

  # No zap stanza required
end
